### ISSUE TITLE
@3x support

### ISSUE THREAD

**Issue by olegam** [steventroughtonsmith/cartool#1]
Any idea how @3x assets are stored? It seems naively looking for assets with a scale factor of 3.0 for the .`kCoreThemeIdiomPhone` does not work: https://github.com/mono0926/cartool/commit/427dbd871985957e2a6e470a3a93debed2d19427

**Comment by OdNairy** [comment]
I found fork that support 3x scale. [Check there.](https://github.com/G-P-S/cartool)

**Comment by Tonyland** [comment]
Crash on start using the 3x support version
